
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action DownloadDirectoryAction;
	
	private global::Gtk.Action SelectFolderAction;
	
	private global::Gtk.Action OpenDownloadsAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label label_app_name;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Entry text_adress;
	
	private global::Gtk.Button button_go;
	
	private global::Gtk.Button button_back;
	
	private global::Gtk.Button button_home;
	
	private global::Gtk.Button button_forward;
	
	private global::Gtk.Button button_DownloadVideo;
	
	private global::Gtk.Button button_downloadAudioSq;
	
	private global::Gtk.Button button_DownloadHQ;
	
	private global::Gtk.VPaned vpaned1;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.ScrolledWindow scrolledWebWindow;
	
	private global::Gtk.ScrolledWindow scrolledListDownlaods;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.DownloadDirectoryAction = new global::Gtk.Action ("DownloadDirectoryAction", global::Mono.Unix.Catalog.GetString ("Download Directory"), null, null);
		this.DownloadDirectoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Download Directory");
		w1.Add (this.DownloadDirectoryAction, null);
		this.SelectFolderAction = new global::Gtk.Action ("SelectFolderAction", global::Mono.Unix.Catalog.GetString ("Select Folder"), null, null);
		this.SelectFolderAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select Folder");
		w1.Add (this.SelectFolderAction, null);
		this.OpenDownloadsAction = new global::Gtk.Action ("OpenDownloadsAction", global::Mono.Unix.Catalog.GetString ("Open Downloads"), null, null);
		this.OpenDownloadsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Downloads");
		w1.Add (this.OpenDownloadsAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Youtube Music Downloader");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_bottom", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='DownloadDirectoryAction' action='DownloadDirectoryAction'><menuitem name='SelectFolderAction' action='SelectFolderAction'/><menuitem name='OpenDownloadsAction' action='OpenDownloadsAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label_app_name = new global::Gtk.Label ();
		this.label_app_name.Name = "label_app_name";
		this.label_app_name.LabelProp = global::Mono.Unix.Catalog.GetString ("Mp3 Downloader");
		this.label_app_name.UseMarkup = true;
		this.hbox2.Add (this.label_app_name);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label_app_name]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Adress:");
		this.hbox3.Add (this.label5);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label5]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.text_adress = new global::Gtk.Entry ();
		this.text_adress.CanFocus = true;
		this.text_adress.Name = "text_adress";
		this.text_adress.IsEditable = true;
		this.text_adress.InvisibleChar = '•';
		this.hbox3.Add (this.text_adress);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.text_adress]));
		w6.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button_go = new global::Gtk.Button ();
		this.button_go.CanFocus = true;
		this.button_go.Name = "button_go";
		this.button_go.UseUnderline = true;
		this.button_go.Label = global::Mono.Unix.Catalog.GetString ("GO!");
		this.hbox3.Add (this.button_go);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_go]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button_back = new global::Gtk.Button ();
		this.button_back.CanFocus = true;
		this.button_back.Name = "button_back";
		this.button_back.UseUnderline = true;
		this.button_back.Label = global::Mono.Unix.Catalog.GetString ("<-");
		this.hbox3.Add (this.button_back);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_back]));
		w8.Position = 4;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button_home = new global::Gtk.Button ();
		this.button_home.CanFocus = true;
		this.button_home.Name = "button_home";
		this.button_home.UseUnderline = true;
		this.button_home.Label = global::Mono.Unix.Catalog.GetString ("Home");
		this.hbox3.Add (this.button_home);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_home]));
		w9.Position = 5;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button_forward = new global::Gtk.Button ();
		this.button_forward.CanFocus = true;
		this.button_forward.Name = "button_forward";
		this.button_forward.UseUnderline = true;
		this.button_forward.Label = global::Mono.Unix.Catalog.GetString ("->");
		this.hbox3.Add (this.button_forward);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_forward]));
		w10.Position = 6;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button_DownloadVideo = new global::Gtk.Button ();
		this.button_DownloadVideo.CanFocus = true;
		this.button_DownloadVideo.Name = "button_DownloadVideo";
		this.button_DownloadVideo.UseUnderline = true;
		this.button_DownloadVideo.Label = global::Mono.Unix.Catalog.GetString ("Download Video");
		this.hbox3.Add (this.button_DownloadVideo);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_DownloadVideo]));
		w11.Position = 7;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button_downloadAudioSq = new global::Gtk.Button ();
		this.button_downloadAudioSq.CanFocus = true;
		this.button_downloadAudioSq.Name = "button_downloadAudioSq";
		this.button_downloadAudioSq.UseUnderline = true;
		this.button_downloadAudioSq.Label = global::Mono.Unix.Catalog.GetString ("Download Mp3 SQ");
		this.hbox3.Add (this.button_downloadAudioSq);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_downloadAudioSq]));
		w12.Position = 8;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button_DownloadHQ = new global::Gtk.Button ();
		this.button_DownloadHQ.CanFocus = true;
		this.button_DownloadHQ.Name = "button_DownloadHQ";
		this.button_DownloadHQ.UseUnderline = true;
		this.button_DownloadHQ.Label = global::Mono.Unix.Catalog.GetString ("Download Mp3 HQ");
		this.hbox3.Add (this.button_DownloadHQ);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button_DownloadHQ]));
		w13.Position = 9;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 361;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 567;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.scrolledWebWindow = new global::Gtk.ScrolledWindow ();
		this.scrolledWebWindow.CanFocus = true;
		this.scrolledWebWindow.Name = "scrolledWebWindow";
		this.scrolledWebWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.hpaned1.Add (this.scrolledWebWindow);
		global::Gtk.Paned.PanedChild w15 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.scrolledWebWindow]));
		w15.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.scrolledListDownlaods = new global::Gtk.ScrolledWindow ();
		this.scrolledListDownlaods.CanFocus = true;
		this.scrolledListDownlaods.Name = "scrolledListDownlaods";
		this.scrolledListDownlaods.ShadowType = ((global::Gtk.ShadowType)(1));
		this.hpaned1.Add (this.scrolledListDownlaods);
		this.vpaned1.Add (this.hpaned1);
		global::Gtk.Paned.PanedChild w17 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.hpaned1]));
		w17.Resize = false;
		this.vbox1.Add (this.vpaned1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vpaned1]));
		w18.Position = 3;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 817;
		this.DefaultHeight = 527;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SelectFolderAction.Activated += new global::System.EventHandler (this.OnSelectFolderActionActivated);
		this.OpenDownloadsAction.Activated += new global::System.EventHandler (this.OnOpenDownloadsActionActivated);
		this.button_go.Clicked += new global::System.EventHandler (this.OnButtonGoClicked);
		this.button_back.Clicked += new global::System.EventHandler (this.OnButtonBackClicked);
		this.button_home.Clicked += new global::System.EventHandler (this.OnButtonHomeClicked);
		this.button_forward.Clicked += new global::System.EventHandler (this.OnButtonForwardClicked);
		this.button_DownloadVideo.Clicked += new global::System.EventHandler (this.OnButtonDownloadVideoClicked);
		this.button_downloadAudioSq.Clicked += new global::System.EventHandler (this.OnButtonDownloadAudioSqClicked);
		this.button_DownloadHQ.Clicked += new global::System.EventHandler (this.OnButtonDownloadHQClicked);
	}
}
